const today = new Date();
  today.setHours(0, 0, 0, 0);

  const sampleContracts = [
    {
      contract_id: 'WC-2026-001',
      po_number: 'PO-2026-0356',
      project_name: 'ระบบ CCTV โรงพยาบาลขอนแก่น',
      customer_name: 'โรงพยาบาลขอนแก่น',
      service_type: 'MA+PM',
      start_date: '2025-01-01',
      end_date: '2026-04-25',
      recipients_sale: 'sale@company.com',
      recipients_eng: 'eng1@company.com,eng2@company.com',
      teams_webhook: 'https://outlook.office.com/webhook/sample1',
      note: 'ดูแลกล้อง CCTV 120 ตัว',
      status: 'active',
      line_group_id: 'C1a2b3c4d5e6f7890abcdef123456789',
      notify_line: true,
    },
    {
      contract_id: 'WC-2026-002',
      po_number: 'PO-2026-0289',
      project_name: 'ระบบ Network มหาวิทยาลัยขอนแก่น',
      customer_name: 'มหาวิทยาลัยขอนแก่น',
      service_type: 'MA',
      start_date: '2025-06-01',
      end_date: '2026-05-15',
      recipients_sale: 'sale2@company.com',
      recipients_eng: 'eng3@company.com',
      teams_webhook: 'https://outlook.office.com/webhook/sample2',
      note: '',
      status: 'active',
      line_group_id: '',
      notify_line: false,
    },
    {
      contract_id: 'WC-2026-003',
      po_number: 'PO-2026-0100',
      project_name: 'ระบบ Firewall การไฟฟ้าส่วนภูมิภาค',
      customer_name: 'การไฟฟ้าส่วนภูมิภาค (กฟภ.)',
      service_type: 'MA+PM',
      start_date: '2026-01-01',
      end_date: '2026-12-31',
      recipients_sale: 'sale@company.com',
      recipients_eng: 'eng1@company.com',
      teams_webhook: 'https://outlook.office.com/webhook/sample3',
      note: '',
      status: 'active',
      line_group_id: 'C9876543210abcdef1234567890abcdef',
      notify_line: true,
    },
    {
      contract_id: 'WC-2026-004',
      po_number: 'PO-2025-0899',
      project_name: 'ระบบ Server ธนาคารกรุงไทย สาขาขอนแก่น',
      customer_name: 'ธนาคารกรุงไทย',
      service_type: 'PM',
      start_date: '2025-01-01',
      end_date: '2026-04-12',
      recipients_sale: 'sale3@company.com',
      recipients_eng: 'eng2@company.com',
      teams_webhook: '',
      note: 'PM ทุก 3 เดือน',
      status: 'active',
      line_group_id: '',
      notify_line: false,
    },
    {
      contract_id: 'WC-2026-005',
      po_number: 'PO-2026-0501',
      project_name: 'ระบบ Wi-Fi โรงเรียนสาธิต มข.',
      customer_name: 'โรงเรียนสาธิต มข.',
      service_type: 'MA',
      start_date: '2026-01-01',
      end_date: '2026-06-30',
      recipients_sale: 'sale4@company.com',
      recipients_eng: 'eng4@company.com',
      teams_webhook: 'https://outlook.office.com/webhook/sample5',
      note: 'ดูแล AP 50 ตัว',
      status: 'active',
      line_group_id: 'Cabcdef1234567890abcdef1234567890',
      notify_line: true,
    },
    {
      contract_id: 'WC-2026-006',
      po_number: 'PO-2026-0620',
      project_name: 'ระบบ UPS ศูนย์ข้อมูล กระทรวงสาธารณสุข',
      customer_name: 'กระทรวงสาธารณสุข',
      service_type: 'PM',
      start_date: '2026-03-01',
      end_date: '2027-02-28',
      recipients_sale: 'sale@company.com',
      recipients_eng: 'eng1@company.com',
      teams_webhook: 'https://outlook.office.com/webhook/sample6',
      note: '',
      status: 'active',
      line_group_id: '',
      notify_line: false,
    },
    {
      contract_id: 'WC-2026-007',
      po_number: 'PO-2026-0710',
      project_name: 'ระบบ Access Control โรงงาน CPF ขอนแก่น',
      customer_name: 'CPF ขอนแก่น',
      service_type: 'MA+PM',
      start_date: '2026-02-01',
      end_date: '2027-01-31',
      recipients_sale: 'sale5@company.com',
      recipients_eng: 'eng5@company.com',
      teams_webhook: '',
      note: '',
      status: 'active',
      line_group_id: '',
      notify_line: false,
    },
    {
      contract_id: 'WC-2025-008',
      po_number: 'PO-2025-0200',
      project_name: 'ระบบ PA โรงพยาบาลศรีนครินทร์',
      customer_name: 'โรงพยาบาลศรีนครินทร์',
      service_type: 'MA',
      start_date: '2024-06-01',
      end_date: '2025-05-31',
      recipients_sale: 'sale@company.com',
      recipients_eng: 'eng1@company.com',
      teams_webhook: '',
      note: '',
      status: 'expired',
      line_group_id: '',
      notify_line: false,
    },
    {
      contract_id: 'WC-2026-009',
      po_number: 'PO-2026-0888',
      project_name: 'ระบบ Digital Signage ห้าง Central ขอนแก่น',
      customer_name: 'Central ขอนแก่น',
      service_type: 'MA',
      start_date: '2026-01-15',
      end_date: '2027-01-14',
      recipients_sale: 'sale6@company.com',
      recipients_eng: 'eng6@company.com,eng7@company.com',
      teams_webhook: 'https://outlook.office.com/webhook/sample9',
      note: '',
      status: 'active',
      line_group_id: 'Cfedcba0987654321fedcba0987654321',
      notify_line: true,
    },
    {
      contract_id: 'WC-2026-010',
      po_number: 'PO-2026-0999',
      project_name: 'ระบบ VoIP สำนักงานจังหวัดขอนแก่น',
      customer_name: 'สำนักงานจังหวัดขอนแก่น',
      service_type: 'MA+PM',
      start_date: '2026-04-01',
      end_date: '2027-03-31',
      recipients_sale: 'sale7@company.com',
      recipients_eng: 'eng8@company.com',
      teams_webhook: 'https://outlook.office.com/webhook/sample10',
      note: '',
      status: 'active',
      line_group_id: '',
      notify_line: false,
    },
  ];

  const sampleLogs = [
    { log_id: 'LOG-001', rule_id: 'NR-001', contract_id: 'WC-2026-001', channel: 'email', status: 'success', error_msg: '', sent_at: '2026-01-25 08:00' },
    { log_id: 'LOG-002', rule_id: 'NR-001', contract_id: 'WC-2026-001', channel: 'teams', status: 'success', error_msg: '', sent_at: '2026-01-25 08:00' },
    { log_id: 'LOG-003', rule_id: 'NR-002', contract_id: 'WC-2026-002', channel: 'email', status: 'success', error_msg: '', sent_at: '2026-02-14 08:00' },
    { log_id: 'LOG-004', rule_id: 'NR-002', contract_id: 'WC-2026-002', channel: 'teams', status: 'failed', error_msg: 'Webhook URL invalid', sent_at: '2026-02-14 08:01' },
    { log_id: 'LOG-005', rule_id: 'NR-003', contract_id: 'WC-2026-004', channel: 'email', status: 'success', error_msg: '', sent_at: '2026-03-13 08:00' },
    { log_id: 'LOG-006', rule_id: 'NR-004', contract_id: 'WC-2026-001', channel: 'email', status: 'success', error_msg: '', sent_at: '2026-02-24 08:00' },
    { log_id: 'LOG-007', rule_id: 'NR-004', contract_id: 'WC-2026-001', channel: 'teams', status: 'success', error_msg: '', sent_at: '2026-02-24 08:00' },
    { log_id: 'LOG-008', rule_id: 'NR-005', contract_id: 'WC-2026-003', channel: 'email', status: 'success', error_msg: '', sent_at: '2026-10-02 08:00' },
    { log_id: 'LOG-009', rule_id: 'NR-001', contract_id: 'WC-2026-001', channel: 'line', status: 'success', error_msg: '', sent_at: '2026-01-25 08:01' },
    { log_id: 'LOG-010', rule_id: 'NR-005', contract_id: 'WC-2026-003', channel: 'line', status: 'success', error_msg: '', sent_at: '2026-10-02 08:01' },
    { log_id: 'LOG-011', rule_id: 'NR-003', contract_id: 'WC-2026-005', channel: 'line', status: 'failed', error_msg: 'Invalid group ID', sent_at: '2026-03-13 08:01' },
  ];

  