// ============================================================
//  Build script — inject environment variables into static dashboard
//  รัน: node build.js  (อยู่ใน dashboard/ เพราะ Vercel Root Directory = dashboard/)
//  Vercel จะรัน script นี้อัตโนมัติผ่าน vercel.json buildCommand
// ============================================================

const fs = require('fs');
const path = require('path');

const GAS_SCRIPT_URL = process.env.GAS_SCRIPT_URL || '';

if (!GAS_SCRIPT_URL) {
  console.warn('[build] ⚠️  GAS_SCRIPT_URL is not set — dashboard will run in demo mode');
}

const configContent = `// ============================================================
//  Auto-generated by build.js — DO NOT EDIT MANUALLY
//  Environment variables injected at build time by Vercel
// ============================================================
window.__ENV__ = {
  GAS_SCRIPT_URL: ${JSON.stringify(GAS_SCRIPT_URL)},
};
`;

// อยู่ใน dashboard/ แล้ว → เขียน config.js ในโฟลเดอร์เดียวกัน
const outPath = path.join(__dirname, 'config.js');
fs.writeFileSync(outPath, configContent, 'utf8');
console.log(`[build] ✅ config.js generated → ${outPath}`);
console.log(`[build]    GAS_SCRIPT_URL: ${GAS_SCRIPT_URL ? GAS_SCRIPT_URL.slice(0, 60) + '...' : '(not set — demo mode)'}`);
